### ISSUE TITLE
Merge this project into simpleflow

### ISSUE THREAD

**Issue by jbbarth** [botify-labs/python-simple-workflow#54]
See https://github.com/botify-labs/simpleflow/issues/76

We often find ourselves modifying this project for things we need a layer up, in simpleflow. This is because the projects are tightly coupled and the things provided here in python-simple-workflow are not enough complete / generic.

Merging the 2 projects would simplify development and encourage us to disambiguate classes responsibilities (we have "Decider" actors on both sides for instance, that don't handle the same things).

Any opinion on this?

**Comment by ybastide** [comment]
:+1:

**Comment by ampelmann** [comment]
:+1:

**Comment by jbbarth** [comment]
Done, closing.
